### ISSUE TITLE
Package reference error for NuGet packages

### ISSUE THREAD

**Issue by Jonathanx11** [RichiePhoebix/SSASActivityMonitor#1]
Hi
I don't use NuGet (or GitHub for that matter) and I get the following error after getting the source code from GitHub and trying to compile in VS2012.4.

Error	1	This project references NuGet package(s) that are missing on this computer. Use NuGet Package Restore to download them.  For more information, see http://go.microsoft.com/fwlink/?LinkID=322105. The missing file is packages\Fody.1.29.4\build\dotnet\Fody.targets.	E:\mDev\ActivityViewer2012\SSASActivityMonitor.csproj	314	5	SSASActivityMonitor

Thanks for pointing me in the right direction
JB

**Comment by RichiePhoebix** [comment]
Hello!

Chances are you don't have nuget installed in Visual Studio. If you open
the package manager (I think it is in the Tools menu in VS) you should be
able to search for it there. Install it (you may need to restart vs) and
try again.

Let me know if this works.

**Comment by Jonathanx11** [comment]
Hi
Thanks, that was the problem. (vs did need a restart btw).
Cheers
JB
