### ISSUE TITLE
Include built output in Git

### ISSUE THREAD

**Issue by gbrueckl** [RichiePhoebix/SSASActivityMonitor#2]
Right now you need to download and build everything on your own which requires VS etc. This might not be installed/available everywhere. It would be great if you could include the built output in the Git-repository so one can simply download the final .exe

**Comment by marcosqlbi** [comment]
The EXE alone might not work if you don't have the proper DLLs, and one of the issues is making a decision about which ones to include. Probably it would be a good idea to create a setup.

**Comment by gbrueckl** [comment]
you could include all the DLLs that you used during the build in the output and provide a ZIP-file containing all necessary files
however, I do not know if it is OK/legal to distribute the DLLs this way

the reason why I am asking is that if I am at a customer site and would need the Activity Monitor, I would prefer a simply setup, ideally a copy or download-only

**Comment by marcosqlbi** [comment]
I get your point. It's in the todo list, but anyone who can contribute to do that would be welcome!

**Comment by gbrueckl** [comment]
:) got your point, give me a second

**Comment by marcosqlbi** [comment]
Thanks for your help!
